### ISSUE TITLE
Support to run the docker-compose of Kafka in Windows 10/11

### ISSUE THREAD

**Issue by hungngomobile** [conduktor/kafka-stack-docker-compose#132]
1. Prepared running environment:
 + My Laptop got 2 network cards: Wifi and Wire.The wifi card is on and connect to internet with IP: 192.168.1.2
 + In file c:\Windows\System32\drivers\etc\hosts, add a line as:
     192.168.1.2       host.docker.internal
 + At PowerShell Command Line of Windows 11:
    Set environment variable by command line:  $env:DOCKER_HOST_IP='192.168.1.2'
 + Beside that my laptop has installed the Hyper-V.
 
2. Run command:
    docker-compose -f .\zk-multiple-kafka-multiple.yml up -d
    
Error logs:
+ zoo1 container logs:
[2023-05-30 12:46:28,147] INFO Received connection request from /172.18.0.2:54454 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
[2023-05-30 12:46:28,149] WARN Cannot open channel to 2 at election address zoo2/172.18.0.4:3888 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:615)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.initiateConnection(QuorumCnxManager.java:383)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$QuorumConnectionReqThread.run(QuorumCnxManager.java:457)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
[2023-05-30 12:46:28,154] INFO Notification: my state:LOOKING; n.sid:3, n.state:LOOKING, n.leader:3, n.round:0x1, n.peerEpoch:0x0, n.zxid:0x0, message format version:0x2, n.config version:0x0 (org.apache.zookeeper.server.quorum.FastLeaderElection)
........................
.......................
[2023-05-30 12:46:28,435] INFO Peer state changed: following - discovery (org.apache.zookeeper.server.quorum.QuorumPeer)
[2023-05-30 12:46:28,437] WARN Unexpected exception, tries=0, remaining init limit=30000, connecting to zoo3/172.18.0.2:2888 (org.apache.zookeeper.server.quorum.Learner)
java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:615)
        at org.apache.zookeeper.server.quorum.Learner.sockConnect(Learner.java:292)
        at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:408)
        at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:366)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
[2023-05-30 12:46:28,541] INFO Successfully connected to leader, using address: zoo3/172.18.0.2:2888 (org.apache.zookeeper.server.quorum.Learner)
[2023-05-30 12:46:28,561] INFO Peer state changed: following - synchronization (org.apache.zookeeper.server.quorum.QuorumPeer)

+ Kafka2 container log:

[2023-05-30 12:46:27,897] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2023-05-30 12:46:27,922] INFO Socket connection established, initiating session, client: /172.18.0.5:47488, server: zoo3/172.18.0.2:2183 (org.apache.zookeeper.ClientCnxn)
[2023-05-30 12:46:27,983] WARN Session 0x0 for sever zoo3/172.18.0.2:2183, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
EndOfStreamException: Unable to read additional data from server sessionid 0x0, likely server has closed socket
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2023-05-30 12:46:28,730] INFO Opening socket connection to server zoo2/172.18.0.4:2182. (org.apache.zookeeper.ClientCnxn)
[2023-05-30 12:46:28,730] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2023-05-30 12:46:28,732] INFO Socket connection established, initiating session, client: /172.18.0.5:35198, server: zoo2/172.18.0.4:2182 (org.apache.zookeeper.ClientCnxn)
[2023-05-30 12:46:28,756] INFO Session establishment complete on server zoo2/172.18.0.4:2182, session id = 0x20002a3d6a20000, negotiated timeout = 40000 (org.apache.zookeeper.ClientCnxn)
[2023-05-30 12:46:28,771] WARN An exception was thrown while closing send thread for session 0x20002a3d6a20000. (org.apache.zookeeper.ClientCnxn)
EndOfStreamException: Unable to read additional data from server sessionid 0x20002a3d6a20000, likely server has closed socket
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2023-05-30 12:46:28,873] INFO Session: 0x20002a3d6a20000 closed (org.apache.zookeeper.ZooKeeper)
[2023-05-30 12:46:28,873] INFO EventThread shut down for session: 0x20002a3d6a20000 (org.apache.zookeeper.ClientCnxn)

**Comment by OneCricketeer** [comment]
Windows isn't the issue. Your Zookeeper container isn't starting, and you've not provided logs for it.

Keep in mind that running the multiple-multiple file will ultimately be slower than the single-single file as you'd be needlessly replicating data on the same machine
